# Podfile Final e Corrigido

# CORREÇÃO 1: Desativa a Nova Arquitetura para garantir compatibilidade.
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# CORREÇÃO 2: Define a versão mínima do iOS para todo o projeto.
platform :ios, '13.4'

target 'TCApp' do
  config = use_native_modules!
  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: false
  )
  use_expo_modules!

  # Bloco que é executado após a instalação dos Pods
  post_install do |installer|
    react_native_post_install(installer)

    # CORREÇÃO 3: Força a versão mínima do iOS em TODAS as dependências (Pods).
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      end
    end

    # CORREÇÃO 4: Adiciona o patch para o erro 'constexpr' do react-native-screens.
    Dir.glob(File.join(installer.sandbox.root, 'Pods/Target Support Files/react-native-screens/**/*.h')).each do |header_path|
      header_contents = File.read(header_path)
      unless header_contents.include?('#if __cplusplus') && header_contents.include?('#endif')
        File.write(header_path, "#if __cplusplus\nextern \"C\" {\n#endif\n#{header_contents}\n#if __cplusplus\n}\n#endif")
      end
    end
  end
end